version: "3.1"

services:
  postgres:
    container_name: wagerdb
    image: postgres:14-alpine
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: wagerdb
      POSTGRES_USER: wager
      POSTGRES_PASSWORD: wager
