// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ContextTx is an autogenerated mock type for the ContextTx type
type ContextTx struct {
	mock.Mock
}

// Commit provides a mock function with given fields: ctx
func (_m *ContextTx) Commit(ctx context.Context) {
	_m.Called(ctx)
}

// NewTx provides a mock function with given fields: ctx
func (_m *ContextTx) NewTx(ctx context.Context) context.Context {
	ret := _m.Called(ctx)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Rollback provides a mock function with given fields: ctx
func (_m *ContextTx) Rollback(ctx context.Context) {
	_m.Called(ctx)
}
