// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "wager-be/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// PurchaseRepository is an autogenerated mock type for the PurchaseRepository type
type PurchaseRepository struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ctx, purchase
func (_m *PurchaseRepository) Insert(ctx context.Context, purchase *domain.Purchase) error {
	ret := _m.Called(ctx, purchase)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Purchase) error); ok {
		r0 = rf(ctx, purchase)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
